### ISSUE TITLE
Errors on tilemap example

### ISSUE THREAD

**Issue by krazyjakee** [endel/joy.js#10]
http://joyjs.org/core/tilemap.html

https://github.com/krazyjakee/jQuest/blob/master/js/init.js
My code isn't so different from the the code in the tutorial, so why am I getting errors?

```
Uncaught TypeError: Cannot read property 'length' of undefined joy.js:5874
```

And on mouseover

```
Uncaught TypeError: Cannot read property 'viewport' of undefined joy.js:7085
```

I've hosted it here for your convenience: http://belynz.com/jake/
If you could take a look I'd be grateful :+1:

**Comment by endel** [comment]
@krazyjakee sorry for the long delay to reply. I've just pushed some fixes and updated the website. Thanks for reporting this!
