### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by odinduclos** [endel/joy.js#11]
Hello your server seems to be down. Cannot access Documentation or API. Excellent lib by the way. Like it so much!

**Comment by endel** [comment]
Hey @odinduclos, thank you for reporting this.

While it isn't possible to access the domain, you could access via github pages here: http://endel.github.io/joy.js/api/

**Comment by odinduclos** [comment]
Thanks a lot for your answer, didn't  saw this documentation before. Once again, good job!

**Comment by endel** [comment]
@odinduclos glad that you liked it. Please let me know if you find any problem.
