### ISSUE TITLE
Sprites hit-box

### ISSUE THREAD

**Issue by odinduclos** [endel/joy.js#12]
Hello, is it me, or the sprite hitbox does not rotate along with the sprite? Is there a special function to call to rotate the hitbox?
Example:
![hit_box_sprite](https://cloud.githubusercontent.com/assets/6941398/5163837/4e885ef0-73d0-11e4-9919-520e3b226f7a.png)
Thank you for your answer!

**Comment by endel** [comment]
Hi @odinduclos,

The [RectCollider](https://github.com/endel/joy.js/blob/master/lib/collider/rect_collider.js) actually isn't respecting the rotation. For now I think you could do one of the following alternatives:
- Use perfect rectangles as colliders
- Create a CircleCollider, which doesn't exists on this library yet.
