### ISSUE TITLE
How to not display Joy.js loading animation...

### ISSUE THREAD

**Issue by mhuusko5** [endel/joy.js#5]
Is there a way? 

P.s. I love this game engine – great work!

**Comment by endel** [comment]
Hey @mhuusko5, you may customize the loading animation by calling setSceneLoader. Currently there is no way to remove the loading animation.

Here is an example:

```
var engine = new Joy.Engine({width: 320, height: 240});
engine.setSceneLoader(function(scene) {
  var progress = new Joy.Text({font: "24px Tahoma", color: "red"});
  progress.bind(Joy.Events.UPDATE, function () {
    this.text = scene.loader.percentage;
  });
  scene.addChild(progress);
});
```

Thanks!

**Comment by mhuusko5** [comment]
Okay cool. Another question - every time I add a child to a scene, the scene fades out/back in. This is fine if you're only adding sprites at the very start of the game, but if you're adding them in game (like what I'm doing – adding bullets to the scene), then it is not good to have the scene going black all the time.
Your thoughts?

**Comment by endel** [comment]
That's not a common behaviour. Could you share your working code via jsfiddle.net or something like that?

**Comment by mhuusko5** [comment]
Nevermind I fixed it. I just disabled the fadein/fadeout code in gotoScene.
But yeah, anytime you do scene.add(something) the screen fadesout/in.

**Comment by endel** [comment]
Could you share your code so I'll check where may be a problem? The behaviour you explained is weird. :)
Thanks!

**Comment by mhuusko5** [comment]
var engine = new Joy.Engine({
        debug: false,
        canvas: canvas
    });

```
engine.setSceneLoader(function (scene) {
});

engine.createScene(function(scene) {
    var someSprite = new Joy.Sprite({
        x: 100,
        y: 100,
        width: 100,
        height: 100,
        src: 'img',
        smooth:true
    });

    var someSpriteIWantToAddLater = new Joy.Sprite({
        x: 200,
        y: 300,
        width: 200,
        height: 200,
        src: 'img',
        smooth:true
    });

    scene.addChild(someSprite);
    //Screen fade in, expected

    setTimeout(function() {
        scene.addChild(someSpriteIWantToAddLater);
        //Screen fade out/in, NOT NORMAL
    }, 10000);
});
```

**Comment by endel** [comment]
Thanks for reporting this @mhuusko5, here is your example with the patch applied. http://jsfiddle.net/endel/LXqxu/
Could you please update your joy.js to v0.2.1?

I'm closing this issue now, but feel free to comment here if you like, or create another issue.
