### ISSUE TITLE
joy.js engine suppresses all keyboard events on window/document

### ISSUE THREAD

**Issue by mhuusko5** [endel/joy.js#7]
It seems that the keyboard module binds to keyboard events in such a way that they are suppressed from their normal behavior.
A page with a joy.js engine instantiated will not respond to normal key combos, and further binds to key presses/releases will not work.

**Comment by endel** [comment]
@mhuusko5 sorry for the long delay to reply. I've released a new version which fixes this. Thank you for reporting.
